name: Build and Release

# runs on every new tag starting with 'v' (e.g. v1.0.0)
on:
  push:
    tags:
      - 'v*'
  # for triggering manually through website
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Android Release APK
        run: ./gradlew assembleRelease

      - name: Sign Android Release APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        env:
          BUILD_TOOLS_VERSION: "35.0.0"
        with:
          releaseDirectory: composeApp/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

  build-desktop:
    name: Build Desktop (${{ matrix.os }})
    # This matrix tells GitHub to run this job 3 separate times on 3 different OS's
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make Gradle executable (Linux/Mac)
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Build Desktop Native Distribution
        run: ./gradlew packageDistributionForCurrentOS

      - name: Upload Desktop Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Desktop-${{ matrix.os }}
          # This grabs the .msi, .dmg, and .deb files generated by Compose
          path: composeApp/build/compose/binaries/main/*/*

  create-release:
    name: Create GitHub Release
    needs: [build-android, build-desktop]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts
          merge-multiple: true

      - name: Create Release & Upload Files
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "GroShare Release ${{ github.ref_name }}"
          body: "Automated release triggered by tag ${{ github.ref_name }}."
          files: release-artifacts/*